name: Run tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
      - name: Install OCaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 4.14.1
          dune-cache: true
      - name: Install OCaml dependencies
        run: opam install . --deps-only --with-test
      - name: Build
        run: opam exec -- dune build
      - name: Test
        run: opam exec -- dune runtest
